### ISSUE TITLE
Refactor API endpoints

### ISSUE THREAD

**Issue by lohrd** [serratus-bio/serratus-db#2]
- Right now, all relevant end points are present on the 'Runs' controller
- To add more cohesion, endpoints relevant to family and accession data should be migrated from the 'Runs' controller to their respective controllers
- Current Endpoint for Accessions: http://serratustest-dev-sumdb.us-east-1.elasticbeanstalk.com/api/runs/get-runs/NC_032111.1
- Example: http://serratustest-dev-sumdb.us-east-1.elasticbeanstalk.com/api/accession/get-accessions/NC_032111.1

**Comment by victorlin** [comment]
We will also have to update the calls to the endpoints in serratus.io: https://github.com/serratus-bio/serratus.io/blob/7e62e1d4/src/SDK/DataSdk.jsx#L4-L17

**Comment by victorlin** [comment]
As a summary, all the relevant objects in the DB are one of these:

1. [SRA accession](https://github.com/serratus-bio/serratus-db/blob/157dd3d0/SerratusTest/Domain/Model/Run.cs)
2. [GenBank accession](https://github.com/serratus-bio/serratus-db/blob/157dd3d0/SerratusTest/Domain/Model/AccessionSection.cs)
3. [Taxonomy family](https://github.com/serratus-bio/serratus-db/blob/157dd3d0/SerratusTest/Domain/Model/FamilySection.cs)

I'd like to establish a naming convention to reduce confusion (`accession` can be ambiguous). These are what I've used on the website:

1. SRA accession: `run` (https://serratus.io/query?run=ERR2756788)
2. GenBank accession: `genbank` (https://serratus.io/query?genbank=EU769558.1)
3. Taxonomy family: `family` (https://serratus.io/query?family=Coronaviridae)

With these names, we can adjust routes accordingly::

- Get data linked to a single SRA accession ([example](https://db.serratus.io/api/runs/get-run/ERR2756788))
    - current route: [`/api/runs/get-run/{sra}`](https://github.com/serratus-bio/serratus-db/blob/157dd3d0/SerratusApi/Controllers/RunsController.cs#L54)
    - new route: `/api/run/get-run/{run}`
- Get list of GenBank accession entries ([example](https://db.serratus.io/api/runs/get-runs/NC_032111.1))
    - current route: [`/api/runs/get-runs/{accession}`](https://github.com/serratus-bio/serratus-db/blob/157dd3d0/SerratusApi/Controllers/RunsController.cs#L54)
    - new route: `/api/genbank/get-runs/{genbank}`
- Get list of Family entries ([example](https://db.serratus.io/api/runs/get-runs-by-family/Coronaviridae))
    - current route: [`/api/runs/get-runs-by-family/{family}`](https://github.com/serratus-bio/serratus-db/blob/157dd3d0/SerratusApi/Controllers/RunsController.cs#L70)
    - new route: `/api/family/get-runs/{family}`

@ababaian @lohrd does this sound good?

**Comment by ababaian** [comment]
This is logical and consistent, 100% agreed.

**Comment by victorlin** [comment]
closed by #7 (thanks @sepetaana!)
