### ISSUE TITLE
family, genbank: add filters for score/cvgpct, pctid

### ISSUE THREAD

**Issue by lohrd** [serratus-bio/serratus-db#5]
### Background

serratus-bio/serratus.io#41 introduced a new component that allows for family-level exploration of data. There are sliders to filter by `pctid` and `score`. There is a button on the Explore page that will link to the Query page, pending these filters.

### Task

Support the following scenarios for the `family` endpoint:

- `/api/family/get-runs/{family}`
- `/api/family/get-runs/{family}?pctId=80-90`
- `/api/family/get-runs/{family}?score=60-100`
- `/api/family/get-runs/{family}?pctId=80-90&score=60-100`

For `genbank`:

- `/api/genbank/get-runs/{genbank}`
- `/api/genbank/get-runs/{genbank}?pctId=80-90`
- `/api/genbank/get-runs/{genbank}?cvgPct=60-100`
- `/api/genbank/get-runs/{genbank}?pctId=80-90&cvgPct=60-100`

**Comment by victorlin** [comment]
### Background

This PR (serratus-bio/serratus.io#41) will introduce a new component that allows for family-level exploration of data. There are sliders to filter by `pctid` and `score`.

### Task

Based on proposed endpoints in #2, we want support for the following scenarios for the `family` endpoint:

- `/api/family/get-runs/{family}`
- `/api/family/get-runs/{family}?pctIdLow=80&pctIdHigh=90`
- `/api/family/get-runs/{family}?scoreLow=60&scoreHigh=100`
- `/api/family/get-runs/{family}?pctIdLow=80&pctIdHigh=90&scoreLow=60&scoreHigh=100`

After this is implemented, we can add a button on the new component that links out to a query representing the slider range filters.

**Comment by victorlin** [comment]
or, this would require some string parsing but it would be more concise:

- `/api/family/get-runs/{family}?pctId=80-90`
- `/api/family/get-runs/{family}?score=60-100`
- `/api/family/get-runs/{family}?pctId=80-90&score=60-100`
